"""
Utility functions for loading ERA5-Land NetCDF data and reshaping to DataFrames.

Used by all analysis scripts (01, 02, 03).
Requires: data/netcdf/{Country}_ERA5Land_monthly.nc  (generated by 00_convert_to_netcdf.py)
"""

import os
import numpy as np
import pandas as pd
import xarray as xr

NETCDF_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'netcdf')

ALL_VARS = [
    'P_mm', 'ET_mm', 'R_sro_mm', 'R_ssro_mm', 'R_mm', 'S_mm',
    'T_C', 'Td_C', 'Rn_sw', 'Rn_lw', 'Wind', 'Ts_C', 'SP'
]

FEATURE_VARS = ['P_mm', 'T_C', 'Td_C', 'Rn_sw', 'Rn_lw', 'Wind', 'Ts_C', 'S_prev']


def load_country_dataset(country):
    """Load NetCDF for one country. Returns xarray Dataset with dims (time, lat, lon)."""
    fpath = os.path.join(NETCDF_DIR, f'{country}_ERA5Land_monthly.nc')
    if not os.path.exists(fpath):
        raise FileNotFoundError(
            f'{fpath} not found. Run scripts/00_convert_to_netcdf.py first.'
        )
    return xr.open_dataset(fpath, mask_and_scale=True)


def dataset_to_dataframe(ds, country, drop_vars=None):
    """
    Reshape xarray Dataset (time, lat, lon) to flat DataFrame.
    Each row = one pixel x one month. Pixels fully outside country mask are dropped.

    Parameters
    ----------
    ds : xr.Dataset
    country : str
    drop_vars : list of str, optional
        Variables to exclude from the output DataFrame.

    Returns
    -------
    pd.DataFrame with columns: time, lat, lon, country, year, month, pixel_id, + all vars
    """
    vars_to_keep = [v for v in ALL_VARS if v in ds and (drop_vars is None or v not in drop_vars)]

    df = ds[vars_to_keep].stack(pixel=('lat', 'lon')).to_dataframe().reset_index()

    # Drop pixels that are entirely masked (ocean / outside boundary)
    valid = df.groupby(['lat', 'lon'])['R_mm'].transform(lambda x: x.notna().any())
    df = df[valid].copy()

    # Drop rows with NaN in the core water balance variables
    df = df.dropna(subset=['P_mm', 'ET_mm', 'R_mm', 'S_mm', 'T_C'])

    df['country']  = country
    df['year']     = df['time'].dt.year
    df['month']    = df['time'].dt.month
    df['pixel_id'] = df['lat'].round(4).astype(str) + '_' + df['lon'].round(4).astype(str)

    return df.reset_index(drop=True)


def add_S_prev(df):
    """
    Add S_prev: soil water storage of the previous month, per pixel.
    Drops the first month of each pixel (no lagged value available).
    """
    df = df.sort_values(['pixel_id', 'time']).copy()
    df['S_prev'] = df.groupby('pixel_id')['S_mm'].shift(1)
    return df.dropna(subset=['S_prev']).reset_index(drop=True)


def add_dS(df):
    """
    Add dS: change in soil water storage from previous month, per pixel.
    dS = S_mm(t) - S_mm(t-1).  Used in water balance: P = ET + R + dS + residual.
    Requires S_prev to already be present (call add_S_prev first).
    """
    df['dS'] = df['S_mm'] - df['S_prev']
    return df


def load_pixel_dataframe(country):
    """
    Full pipeline: NetCDF -> pixel-level monthly DataFrame ready for XGBoost.

    Returns DataFrame with columns:
        time, lat, lon, country, year, month, pixel_id,
        P_mm, ET_mm, R_sro_mm, R_ssro_mm, R_mm, S_mm,
        T_C, Td_C, Rn_sw, Rn_lw, Wind, Ts_C, SP,
        S_prev, dS
    """
    ds = load_country_dataset(country)
    df = dataset_to_dataframe(ds, country)
    df = add_S_prev(df)
    df = add_dS(df)
    return df


def load_country_mean_timeseries(country):
    """
    Return spatially averaged monthly time series (one row per month, 312 rows total).
    Computes the spatial mean directly from the xarray Dataset to preserve all 312 months
    (pixel-level approach drops the first month of each pixel due to S_prev lag).

    Returns pd.DataFrame with columns: date, year, month, country, + all vars, dS, S_prev
    """
    ds = load_country_dataset(country)
    # skipna=True automatically ignores masked pixels (ocean / outside boundary)
    mean_ts = ds.mean(dim=['lat', 'lon'], skipna=True).to_dataframe().reset_index()
    mean_ts = mean_ts.rename(columns={'time': 'date'})
    mean_ts['year']    = mean_ts['date'].dt.year
    mean_ts['month']   = mean_ts['date'].dt.month
    mean_ts['country'] = country
    mean_ts['dS']      = mean_ts['S_mm'].diff()
    mean_ts['S_prev']  = mean_ts['S_mm'].shift(1)
    return mean_ts.reset_index(drop=True)
